const { ROLES } = require("../../config/roles.constants");

const RFQ_ACCESS_RULES = Object.freeze({
  LIST: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PROCUREMENT_OFFICER, ROLES.VENDOR],
  VIEW: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PROCUREMENT_OFFICER, ROLES.VENDOR],
  CREATE: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  UPDATE: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  DELETE: [ROLES.ADMIN],
  OPEN: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  CLOSE: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  CANCEL: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  ASSIGN: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  REMOVE: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
});

module.exports = { RFQ_ACCESS_RULES };