const { ROLES } = require("../../../config/roles.constants");

const VENDOR_ACCESS_RULES = Object.freeze({
  LIST: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PROCUREMENT_OFFICER],
  CREATE: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  VIEW: [ROLES.ADMIN, ROLES.MANAGER, ROLES.PROCUREMENT_OFFICER, ROLES.VENDOR],
  UPDATE: [ROLES.ADMIN, ROLES.PROCUREMENT_OFFICER],
  DELETE: [ROLES.ADMIN],
  STATUS: [ROLES.ADMIN],
  VERIFY: [ROLES.ADMIN],
  BLACKLIST: [ROLES.ADMIN],
});

module.exports = { VENDOR_ACCESS_RULES };